# Generated by Django 3.0.8 on 2020-07-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(blank=True, max_length=40, null=True, verbose_name='ticker')),
                ('value', models.FloatField(blank=True, null=True, verbose_name='value')),
            ],
        ),
    ]
