# Generated by Django 3.0.8 on 2020-07-31 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positions',
            name='value',
        ),
        migrations.AddField(
            model_name='positions',
            name='asset_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='asset_id'),
        ),
        migrations.AddField(
            model_name='positions',
            name='num_of_shares',
            field=models.IntegerField(blank=True, null=True, verbose_name='num_of_shares'),
        ),
        migrations.AddField(
            model_name='positions',
            name='pos_type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='pos_type'),
        ),
        migrations.AddField(
            model_name='positions',
            name='position_value',
            field=models.FloatField(blank=True, null=True, verbose_name='position_value'),
        ),
        migrations.AddField(
            model_name='positions',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='price'),
        ),
    ]
