# Generated by Django 3.0.8 on 2020-07-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200731_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='trade_id')),
                ('asset_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='asset_id')),
                ('trade_type', models.CharField(blank=True, max_length=40, null=True, verbose_name='asset_id')),
                ('num_of_shares', models.IntegerField(blank=True, max_length=40, null=True, verbose_name='asset_id')),
                ('price', models.FloatField(blank=True, null=True, verbose_name='price')),
                ('tot_price', models.FloatField(blank=True, null=True, verbose_name='tot_price')),
                ('trade_time', models.CharField(blank=True, max_length=40, null=True, verbose_name='trade_time')),
            ],
        ),
        migrations.RenameModel(
            old_name='Positions',
            new_name='Position',
        ),
    ]
