# Generated by Django 3.0.8 on 2020-07-31 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200731_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='num_of_shares',
            field=models.IntegerField(blank=True, null=True, verbose_name='asset_id'),
        ),
    ]
