# Generated by Django 3.0.8 on 2020-08-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200731_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForeignExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, max_length=40, null=True, verbose_name='country_code')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='date_')),
                ('exchange_rate', models.FloatField(blank=True, null=True, verbose_name='exchange_rate')),
                ('thirty_day_rate', models.FloatField(blank=True, null=True, verbose_name='thirty_day_rate')),
                ('ninety_day_rate', models.FloatField(blank=True, null=True, verbose_name='ninety_day_rate')),
                ('one_eighty_day_rate', models.FloatField(blank=True, null=True, verbose_name='one_eighty_day_rate')),
                ('one_year_rate', models.FloatField(blank=True, null=True, verbose_name='one_year_rate')),
                ('two_year_rate', models.FloatField(blank=True, null=True, verbose_name='two_year_rate')),
                ('three_year_rate', models.FloatField(blank=True, null=True, verbose_name='three_year_rate')),
                ('five_year_rate', models.FloatField(blank=True, null=True, verbose_name='five_year_rate')),
                ('seven_year_rate', models.FloatField(blank=True, null=True, verbose_name='seven_year_rate')),
                ('ten_year_rate', models.FloatField(blank=True, null=True, verbose_name='ten_year_rate')),
                ('twenty_year_rate', models.FloatField(blank=True, null=True, verbose_name='twenty_year_rate')),
                ('thirty_year_rate', models.FloatField(blank=True, null=True, verbose_name='thirty_year_rate')),
            ],
        ),
        migrations.CreateModel(
            name='MarketData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='asset_id')),
                ('date', models.DateTimeField(blank=True, null=True, verbose_name='date_')),
                ('open_price', models.FloatField(blank=True, null=True, verbose_name='open_price')),
                ('close_price', models.FloatField(blank=True, null=True, verbose_name='close_price')),
                ('intra_high', models.FloatField(blank=True, null=True, verbose_name='intra_high')),
                ('intra_low', models.FloatField(blank=True, null=True, verbose_name='intra_low')),
                ('dividend', models.FloatField(blank=True, null=True, verbose_name='dividend')),
                ('adj_factor', models.FloatField(blank=True, null=True, verbose_name='adj_factor')),
                ('num_of_shares', models.IntegerField(blank=True, null=True, verbose_name='asset_id')),
                ('tot_value', models.FloatField(blank=True, null=True, verbose_name='tot_value')),
                ('cap', models.FloatField(blank=True, null=True, verbose_name='cao')),
                ('usd_shr', models.FloatField(blank=True, null=True, verbose_name='usd_shr')),
            ],
        ),
    ]
