# Generated by Django 3.0.8 on 2020-08-03 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_foreignexchange_marketdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='trade_time',
        ),
    ]
