# Generated by Django 3.0.8 on 2020-08-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_trade_trade_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date_'),
        ),
    ]
