# Generated by Django 3.0.8 on 2020-08-07 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200807_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(blank=True, max_length=40, null=True, verbose_name='asset_id')),
                ('ticker', models.CharField(blank=True, max_length=40, null=True, verbose_name='ticker')),
                ('conid', models.CharField(blank=True, max_length=40, null=True, verbose_name='conid')),
                ('cusip', models.CharField(blank=True, max_length=40, null=True, verbose_name='cusip')),
                ('valid_date', models.DateField(default=django.utils.timezone.now)),
                ('industry_code', models.CharField(blank=True, max_length=40, null=True, verbose_name='industry_code')),
                ('country_code', models.CharField(blank=True, max_length=40, null=True, verbose_name='country_code')),
                ('prim_exch', models.CharField(blank=True, max_length=40, null=True, verbose_name='prim_exch')),
                ('currency', models.CharField(blank=True, max_length=40, null=True, verbose_name='currency')),
                ('flag', models.CharField(blank=True, max_length=40, null=True, verbose_name='flag')),
            ],
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
