# Generated by Django 3.0.8 on 2020-08-11 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20200807_1848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='pos_type',
            new_name='asset_type',
        ),
    ]
