# Generated by Django 3.0.8 on 2020-08-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200811_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='asset id'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='country_code',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='country code'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='industry_code',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='industry code'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='prim_exch',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='prim exch'),
        ),
        migrations.AlterField(
            model_name='foreignexchange',
            name='country_code',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='country code'),
        ),
        migrations.AlterField(
            model_name='foreignexchange',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='foreignexchange',
            name='exchange_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='exchange rate'),
        ),
        migrations.AlterField(
            model_name='foreignexchange',
            name='five_year_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='five year rate'),
        ),
        migrations.AlterField(
            model_name='foreignexchange',
            name='ninety_day_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='ninety day rate'),
        ),
        migrations.AlterField(
            model_name='foreignexchange',
            name='one_eighty_day_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='one eighty day rate'),
        ),
        migrations.AlterField(
            model_name='foreignexchange',
            name='one_year_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='one year rate'),
        ),
        migrations.AlterField(
            model_name='foreignexchange',
            name='seven_year_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='seven year rate'),
        ),
        migrations.AlterField(
            model_name='foreignexchange',
            name='ten_year_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='ten year rate'),
        ),
        migrations.AlterField(
            model_name='foreignexchange',
            name='thirty_day_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='thirty day rate'),
        ),
        migrations.AlterField(
            model_name='foreignexchange',
            name='thirty_year_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='thirty year rate'),
        ),
        migrations.AlterField(
            model_name='foreignexchange',
            name='three_year_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='three year rate'),
        ),
        migrations.AlterField(
            model_name='foreignexchange',
            name='twenty_year_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='twenty year rate'),
        ),
        migrations.AlterField(
            model_name='foreignexchange',
            name='two_year_rate',
            field=models.FloatField(blank=True, null=True, verbose_name='two year rate'),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='adj_factor',
            field=models.FloatField(blank=True, null=True, verbose_name='adj factor'),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='asset_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='asset id'),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='close_price',
            field=models.FloatField(blank=True, null=True, verbose_name='close price'),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='intra_high',
            field=models.FloatField(blank=True, null=True, verbose_name='intra high'),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='intra_low',
            field=models.FloatField(blank=True, null=True, verbose_name='intra low'),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='num_of_shares',
            field=models.IntegerField(blank=True, null=True, verbose_name='asset id'),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='open_price',
            field=models.FloatField(blank=True, null=True, verbose_name='open price'),
        ),
        migrations.AlterField(
            model_name='marketdata',
            name='usd_shr',
            field=models.FloatField(blank=True, null=True, verbose_name='usd shr'),
        ),
        migrations.AlterField(
            model_name='position',
            name='asset_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='asset id'),
        ),
        migrations.AlterField(
            model_name='position',
            name='asset_type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='asset type'),
        ),
        migrations.AlterField(
            model_name='position',
            name='num_of_shares',
            field=models.IntegerField(blank=True, null=True, verbose_name='num of shares'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_value',
            field=models.FloatField(blank=True, null=True, verbose_name='position value'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='asset_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='asset id'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_id',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='trade id'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_type',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='asset id'),
        ),
    ]
