# Generated by Django 3.0.8 on 2020-08-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20200817_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='trade_status',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='status'),
        ),
    ]
