# Generated by Django 3.0.8 on 2020-08-18 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_trade_trade_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='trade_time',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='date time'),
        ),
    ]
