[
    {
        "execution_id": "string",
        "symbol": "string",
        "side": "string",
        "order_description": "string",
        "trade_time": "string",
        "trade_time_r": 0,
        "size": "string",
        "price": "string",
        "submitter": "string",
        "exchange": "string",
        "comission": 0,
        "net_amount": 0,
        "account": "string",
        "company_name": "string",
        "contract_description_1": "string",
        "sec_type": "string",
        "conidex": "string",
        "position": "string",
        "clearing_id": "string",
        "clearing_name": "string",
        "order_ref": "string",
    }
]
